sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install scipy
  - pip install matplotlib

script:
  - pytest --cov=./

after_success:
  - codecov
