name: geoist
channels:
        - conda-forge
        - defaults
dependencies:
        - python>=3.5
          #        - impactutils , not used
        - ipython
          #        - libcomcat  , not used
          #        - gdal  , not used
        - pip:
          #          - Cartopy , not used
          #          - obspy , not used
          - Shapely
            #          - scipy , dependency of pandas
          - pytest
          - pandas
            #          - matplotlib , dependency of pandas
            #          - h5py , dependency of rasterio
            #          - numpy , dependency of pandas and scipy
            #          - pygmi , not used
          - MarkDown
          - rasterio
          - Cython
          - future
