package:
  name: geoist
  version: 0.0.1

source:
  path: ../

build:
  noarch_python: True

requirements:
  build:
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - ipython
    - gdal
    - Shapely
    - pytest
    - pandas
    - numba
    - MarkDown
    - rasterio
    - future
    - numpy
    - scipy
    - matplotlib

about:
  home: https://github.com/igp-gravity/geoist
  license: MIT License
